# 01. 데이터 파이프라인

## 주요 피처
| 피처 | 설명 |
|------|------|
| drop_distance_from_path | 비행기 경로에서 낙하 지점까지 수직 거리 |
| early_enemy_density | 낙하 직후 반경 500m 내 적 수 |
| rotation_timing_score | 자기장 선점 vs 후행 비율 (0=선점, 1=후행) |
| vehicle_use_ratio | 차량 이동 비율 |
| bluezone_exposure_ratio | 블루존 체류 비율 |
| safezone_proximity_mean | 안전구역 중심까지 평균 거리 |
| safezone_edge_ratio | 안전구역 반경 대비 상대 거리 |
| altitude_variance | 고도 변화량 (지형 활용도) |
| max_vehicle_distance | 낙하 지점 대비 최대 차량 이동 거리 |

**파일 구조:** `temp_parquet_files_{server}_{ymd}/{MAP_NAME}_{uuid}.parquet` (1파일 = 1매치)

In [1]:
# 공통 설정 로드
# BASE_DIR / OUTPUT_DIR / DATE_START / DATE_END / MAP_NAME 등 config.py에서 관리
%run config.py

import glob
import duckdb
import pandas as pd
import numpy as np
from tqdm import tqdm
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# DuckDB 연결 (전역 재사용)
con = duckdb.connect(':memory:')
con.execute(f'PRAGMA threads={DUCKDB_THREADS}; PRAGMA memory_limit="{DUCKDB_MEMORY}";')

print(f'DuckDB version: {duckdb.__version__}')

   config.py 로드 완료
   BASE_DIR  : C:\배그분석
   DATE      : 20260212 ~ 20260227
   MAPS      : ['Erangel', 'Miramar', 'Taego', 'Rondo']
DuckDB version: 1.4.4

In [2]:
def get_match_parquet_files(map_name, date_start, date_end):
    """날짜 범위 내 매치 parquet 파일 수집
    파일 구조: temp_parquet_files_{server}_{ymd}/{MAP_NAME}_{uuid}.parquet
    """
    files = []
    for date in pd.date_range(date_start, date_end):
        ymd = date.strftime('%Y%m%d')
        for server in ['kakao', 'steam']:
            folder = Path(BASE_DIR) / f'temp_parquet_files_{server}_{ymd}'
            if not folder.exists():
                continue
            files.extend(sorted(folder.glob(f'{map_name}_*.parquet')))
    return files


def extract_match_id(filepath, map_name):
    """파일명에서 matchId(uuid) 추출
    파일명: Erangel_047584e1-2c6e-4ae4-bb66-e263beb868aa.parquet
    -> 047584e1-2c6e-4ae4-bb66-e263beb868aa
    split('_')[1] 은 uuid 안에 _ 가 없을때만 안전
    -> map_name + '_' prefix 제거 방식으로 안전하게 추출
    """
    return Path(filepath).stem[len(map_name) + 1:]  # 'Erangel_' 이후 전체


PARQUETS = get_match_parquet_files(MAP_NAME, DATE_START, DATE_END)
print(f'매치 파일 수: {len(PARQUETS)}')

# matchId 추출 검증
if PARQUETS:
    sample_id = extract_match_id(PARQUETS[0], MAP_NAME)
    print(f'샘플 matchId: {sample_id} (길이: {len(sample_id)})')
    # uuid 형식 검증 (8-4-4-4-12)
    parts = sample_id.split('-')
    if len(parts) == 5:
        print('uuid 형식 정상')
    else:
        print(f'경고: uuid 형식 이상 - {sample_id}')

매치 파일 수: 3463
샘플 matchId: 01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac (길이: 36)
uuid 형식 정상

In [3]:
# STEP 1: 낙하 지점 추출
# LogParachuteLanding 에서 플레이어당 첫 번째만 사용 (재낙하 제외)
print('낙하 지점 추출 중')

drop_list = []
skip_count = 0

for f in tqdm(PARQUETS):
    match_id = extract_match_id(f, MAP_NAME)
    fsql = str(f).replace('\\', '/')

    df = con.execute(f"""
        SELECT
            character_accountId AS accountId,
            character_name      AS playerName,
            character_teamId    AS teamId,
            character_location_x AS x,
            character_location_y AS y,
            _D
        FROM read_parquet('{fsql}')
        WHERE _T = 'LogParachuteLanding'
          AND character_accountId IS NOT NULL
          AND character_location_x IS NOT NULL
    """).fetchdf()

    if df.empty:
        skip_count += 1
        continue

    # 플레이어당 첫 번째 낙하만 사용
    df = df.sort_values('_D').drop_duplicates('accountId', keep='first')
    df['matchId'] = match_id
    drop_list.append(df[['matchId','accountId','playerName','teamId','x','y']])

df_drop = pd.concat(drop_list, ignore_index=True)
print(f'낙하 지점: {len(df_drop):,}명  |  매치: {df_drop["matchId"].nunique():,}개  |  스킵: {skip_count}개')
display(df_drop.head(3))

낙하 지점 추출 중

100%|██████████| 3463/3463 [00:27<00:00, 126.48it/s]

낙하 지점: 235,522명  |  매치: 3,463개  |  스킵: 0개

,matchId,accountId,playerName,teamId,x,y
0,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac,account.ea72c1bb653648c6877ae1bd79c9af1a,SxxHnxMxx,15.0,179705.703125,630811.875
1,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac,account.6cd69a93ab7f4fc19730c59f34134261,youudonthavemom,10.0,172562.031250,613398.750
2,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac,account.e92917d5921845aca318975e77942cb6,MaxDowman,10.0,171455.468750,620891.250

In [4]:
# STEP 2: 비행기 경로 복원 + 낙하 거리 계산
#
# isGame 0.1 구간에서 z값이 최댓값 기준 500 이내인 레코드 = 비행 중
# arg_min/arg_max: DuckDB 0.8+ 지원. 미지원시 ORDER BY + FIRST/LAST 대체
print('비행기 경로 추출 중')

# DuckDB arg_min 지원 여부 확인
try:
    con.execute("SELECT arg_min(1, 1)").fetchone()
    USE_ARGMIN = True
    print(f'arg_min 지원 (DuckDB {duckdb.__version__})')
except Exception:
    USE_ARGMIN = False
    print('arg_min 미지원 -> FIRST/LAST 방식 사용')

air_list = []
skip_count = 0

for f in tqdm(PARQUETS):
    match_id = extract_match_id(f, MAP_NAME)
    fsql = str(f).replace('\\', '/')

    if USE_ARGMIN:
        q = f"""
            WITH base AS (
                SELECT character_location_x AS x,
                       character_location_y AS y,
                       character_location_z AS z,
                       elapsedTime
                FROM read_parquet('{fsql}')
                WHERE _T = 'LogPlayerPosition'
                  AND common_isGame BETWEEN 0.05 AND 0.15
                  AND character_location_x IS NOT NULL
                  AND character_location_z IS NOT NULL
            ),
            flying AS (
                SELECT * FROM base
                WHERE z >= (SELECT MAX(z) FROM base) - 500
            )
            SELECT
                arg_min(x, elapsedTime) AS x_start,
                arg_min(y, elapsedTime) AS y_start,
                arg_max(x, elapsedTime) AS x_end,
                arg_max(y, elapsedTime) AS y_end,
                COUNT(*) AS n_flying
            FROM flying
        """
    else:
        q = f"""
            WITH base AS (
                SELECT character_location_x AS x,
                       character_location_y AS y,
                       character_location_z AS z,
                       elapsedTime
                FROM read_parquet('{fsql}')
                WHERE _T = 'LogPlayerPosition'
                  AND common_isGame BETWEEN 0.05 AND 0.15
                  AND character_location_x IS NOT NULL
                  AND character_location_z IS NOT NULL
            ),
            flying AS (
                SELECT * FROM base
                WHERE z >= (SELECT MAX(z) FROM base) - 500
                ORDER BY elapsedTime
            )
            SELECT
                FIRST(x) AS x_start,
                FIRST(y) AS y_start,
                LAST(x)  AS x_end,
                LAST(y)  AS y_end,
                COUNT(*) AS n_flying
            FROM flying
        """

    df = con.execute(q).fetchdf()

    if df.empty or df['x_start'].isna().all():
        skip_count += 1
        continue

    # 시작점 = 끝점이면 경로 정보 없음 (비행 구간이 너무 짧은 매치)
    if df['x_start'].iloc[0] == df['x_end'].iloc[0] and df['y_start'].iloc[0] == df['y_end'].iloc[0]:
        skip_count += 1
        continue

    df['matchId'] = match_id
    air_list.append(df)

df_air = pd.concat(air_list, ignore_index=True)
print(f'경로 복원: {len(df_air):,}개 매치  |  스킵: {skip_count}개')
display(df_air.head(3))


def point_to_line_dist(px, py, x1, y1, x2, y2):
    """점(px,py)에서 직선 (x1,y1)-(x2,y2)까지 수직 거리"""
    dx, dy = x2 - x1, y2 - y1
    len_sq = dx*dx + dy*dy
    if len_sq == 0:
        return np.sqrt((px-x1)**2 + (py-y1)**2)
    t = ((px-x1)*dx + (py-y1)*dy) / len_sq
    return np.sqrt((px-(x1+t*dx))**2 + (py-(y1+t*dy))**2)


path_dict = df_air.set_index('matchId').to_dict('index')

df_drop['drop_distance_from_path'] = df_drop.apply(
    lambda r: point_to_line_dist(
        r['x'], r['y'],
        path_dict[r['matchId']]['x_start'], path_dict[r['matchId']]['y_start'],
        path_dict[r['matchId']]['x_end'],   path_dict[r['matchId']]['y_end'],
    ) / 100 if r['matchId'] in path_dict else np.nan,  # cm → m
    axis=1
)

valid = df_drop['drop_distance_from_path'].notna().sum()
print(f'낙하 거리 계산: {valid:,}/{len(df_drop):,}')
print(f'평균: {df_drop["drop_distance_from_path"].mean():.1f}m  '
      f'최대: {df_drop["drop_distance_from_path"].max():.1f}m  '
      f'최소: {df_drop["drop_distance_from_path"].min():.1f}m')

비행기 경로 추출 중
arg_min 지원 (DuckDB 1.4.4)

100%|██████████| 3463/3463 [00:14<00:00, 237.10it/s]

경로 복원: 3,460개 매치  |  스킵: 3개

,x_start,y_start,x_end,y_end,n_flying,matchId
0,80804.500,883259.000,602225.8125,172566.18750,254,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac
1,939323.875,632995.375,114336.8125,483029.71875,231,01a58e2c-d5b5-4741-9c2b-5ca94b6873fb
2,840689.250,789717.250,219559.0000,238775.81250,234,046d6575-7184-4e61-bbc9-6ba9b7e30339

낙하 거리 계산: 235,514/235,522
평균: 768.0m  최대: 3721.3m  최소: 0.0m

In [5]:
# STEP 3: 초기 적 밀도 계산
# isGame 1.0 이상 1.5 미만 구간의 위치 median 기준
# 낙하 지점 반경 500m 내 적 팀 플레이어 수
# BETWEEN 1.0 AND 1.5 는 1.5 포함 -> >= 1.0 AND < 1.5 사용
print('초기 적 밀도 계산 중')

density_rows = []
skip_count   = 0

for f in tqdm(PARQUETS):
    match_id = extract_match_id(f, MAP_NAME)
    fsql = str(f).replace('\\', '/')

    df = con.execute(f"""
        SELECT
            character_accountId AS accountId,
            character_teamId    AS teamId,
            character_location_x AS x,
            character_location_y AS y
        FROM read_parquet('{fsql}')
        WHERE _T = 'LogPlayerPosition'
          AND common_isGame >= 1.0
          AND common_isGame <  1.5
          AND character_accountId IS NOT NULL
          AND character_location_x IS NOT NULL
    """).fetchdf()

    if df.empty:
        skip_count += 1
        continue

    df_med = df.groupby(['accountId','teamId'])[['x','y']].median().reset_index()
    arr   = df_med[['x','y']].to_numpy()
    teams = df_med['teamId'].to_numpy()
    aids  = df_med['accountId'].to_numpy()

    # 낙하 지점 기준으로 계산 (isGame 1.0 초기 위치가 아닌 실제 낙하 좌표)
    match_drop = df_drop[df_drop['matchId'] == match_id][['accountId','teamId','x','y']]

    if match_drop.empty:
        # LogParachuteLanding 이 없는 매치는 초기 위치로 대체
        for i in range(len(df_med)):
            dist = np.sqrt(((arr - arr[i])**2).sum(axis=1))
            enemy_cnt = int(((dist <= 500) & (teams != teams[i])).sum())
            density_rows.append((match_id, aids[i], enemy_cnt))
    else:
        # 낙하 지점 기준 계산
        for _, drow in match_drop.iterrows():
            px, py  = drow['x'], drow['y']
            my_team = drow['teamId']
            aid     = drow['accountId']
            # 초기 위치가 있는 플레이어 중 적 팀만
            mask = teams != my_team
            if mask.sum() == 0:
                enemy_cnt = 0
            else:
                dist = np.sqrt(((arr[mask] - [px, py])**2).sum(axis=1))
                enemy_cnt = int((dist <= 50000).sum())  # 500m = 50000cm
            density_rows.append((match_id, aid, enemy_cnt))

df_density = pd.DataFrame(density_rows, columns=['matchId','accountId','early_enemy_density'])
print(f'완료: {len(df_density):,}명  |  스킵: {skip_count}개  |  평균 적 수(반경 500m): {df_density["early_enemy_density"].mean():.2f}명')
display(df_density.head(3))

초기 적 밀도 계산 중

100%|██████████| 3463/3463 [01:09<00:00, 49.59it/s]

완료: 235,518명  |  스킵: 2개  |  평균 적 수(반경 500m): 5.12명

,matchId,accountId,early_enemy_density
0,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac,account.ea72c1bb653648c6877ae1bd79c9af1a,11
1,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac,account.6cd69a93ab7f4fc19730c59f34134261,12
2,01a4a247-7e5a-4835-a2f7-a3f7c9fb2aac,account.e92917d5921845aca318975e77942cb6,12

In [6]:
# STEP 4: 전체 위치 데이터 + 자기장 정보 조인
#
# LogGameStatePeriodic 의 자기장 정보를 LogPlayerPosition 과
# 매치 단위 merge_asof (direction='backward') 로 조인
# isGame >= 1.0 필터 필수 (비행기 구간 제외)
print('위치 + 자기장 조인 중')

pos_all = []
empty_pos = 0
empty_gs  = 0

for f in tqdm(PARQUETS):
    match_id = extract_match_id(f, MAP_NAME)
    fsql = str(f).replace('\\', '/')

    # 1) 플레이어 위치 (isGame >= 1.0 필터 필수)
    df_pos = con.execute(f"""
        SELECT
            character_accountId      AS accountId,
            character_location_x     AS x,
            character_location_y     AS y,
            character_location_z     AS z,
            character_isInBlueZone   AS isInBlueZone,
            character_isInVehicle    AS isInVehicle,
            common_isGame            AS isGame,
            TRY_CAST(elapsedTime AS DOUBLE) AS elapsedTime
        FROM read_parquet('{fsql}')
        WHERE _T = 'LogPlayerPosition'
          AND common_isGame >= 1.0
          AND character_accountId IS NOT NULL
          AND character_location_x IS NOT NULL
          AND TRY_CAST(elapsedTime AS DOUBLE) IS NOT NULL
    """).fetchdf()

    if df_pos.empty:
        empty_pos += 1
        continue

    df_pos['matchId'] = match_id

    # 2) 자기장 정보
    # gameState_elapsedTime 이 없으면 elapsedTime 으로 fallback
    df_gs = con.execute(f"""
        SELECT
            TRY_CAST(
                COALESCE(gameState_elapsedTime, elapsedTime)
            AS DOUBLE) AS gs_time,
            gameState_safetyZonePosition_x AS safe_x,
            gameState_safetyZonePosition_y AS safe_y,
            gameState_safetyZoneRadius     AS safe_radius
        FROM read_parquet('{fsql}')
        WHERE _T = 'LogGameStatePeriodic'
          AND gameState_safetyZonePosition_x IS NOT NULL
          AND TRY_CAST(
                COALESCE(gameState_elapsedTime, elapsedTime)
              AS DOUBLE) IS NOT NULL
    """).fetchdf()

    if df_gs.empty:
        empty_gs += 1
        df_pos[['safe_x','safe_y','safe_radius']] = np.nan
        pos_all.append(df_pos)
        continue

    df_gs  = df_gs.sort_values('gs_time').reset_index(drop=True)
    df_pos = df_pos.sort_values('elapsedTime').reset_index(drop=True)

    # 3) merge_asof: 각 위치 기록에 직전 자기장 정보 조인
    merged = pd.merge_asof(
        df_pos, df_gs,
        left_on='elapsedTime', right_on='gs_time',
        direction='backward'
    ).drop(columns='gs_time')

    # 4) pos 가 gs 보다 이른 구간 (게임 초반) -> 첫 번째 gs 값으로 채움
    first_gs = df_gs.iloc[0]
    merged['safe_x']      = merged['safe_x'].fillna(first_gs['safe_x'])
    merged['safe_y']      = merged['safe_y'].fillna(first_gs['safe_y'])
    merged['safe_radius'] = merged['safe_radius'].fillna(first_gs['safe_radius'])

    pos_all.append(merged)

if not pos_all:
    raise ValueError('pos_all 이 비었습니다. 컬럼명/필터 조건을 확인하세요.')

df_pos_full = pd.concat(pos_all, ignore_index=True)
print(f'조인 완료: {len(df_pos_full):,}행')
print(f'empty pos: {empty_pos}  empty gs: {empty_gs}')
print(f'safe_x null: {df_pos_full["safe_x"].isna().mean():.1%}')

# bool 변환
df_pos_full['isInBlueZone'] = df_pos_full['isInBlueZone'].astype(str).str.lower().isin(['true','1'])
df_pos_full['isInVehicle']  = df_pos_full['isInVehicle'].astype(str).str.lower().isin(['true','1'])

# 안전구역 중심 거리
df_pos_full['dist_to_safe_center'] = np.sqrt(
    (df_pos_full['x'] - df_pos_full['safe_x'])**2 +
    (df_pos_full['y'] - df_pos_full['safe_y'])**2
) / 100  # cm → m
print('처리 완료')

위치 + 자기장 조인 중

100%|██████████| 3463/3463 [00:43<00:00, 80.20it/s]

조인 완료: 18,548,969행
empty pos: 0  empty gs: 0
safe_x null: 0.0%
처리 완료

In [7]:
# STEP 5: 차량 이동 피처
# LogVehicleRide / LogVehicleLeave 위치 기준
# 낙하 지점 대비 최대 이동 거리 계산
# -> 비행기 경로 기준 낙하 거리보다 더 멀리 이동한 사람 = 차량 활용형
print('차량 이동 계산 중')

# 실제 이벤트명 확인 (첫 파일에서)
fsql_sample = str(PARQUETS[0]).replace('\\','/')
df_veh_evt = con.execute(f"""
    SELECT _T, COUNT(*) AS n
    FROM read_parquet('{fsql_sample}')
    WHERE _T LIKE '%Vehicle%'
    GROUP BY 1
""").fetchdf()
print('차량 이벤트명:')
display(df_veh_evt)

VEH_EVENTS = tuple(df_veh_evt['_T'].tolist())

veh_list = []

for f in tqdm(PARQUETS):
    match_id = extract_match_id(f, MAP_NAME)
    fsql = str(f).replace('\\', '/')

    if not VEH_EVENTS:
        continue

    evt_filter = ' OR '.join([f"_T = '{e}'" for e in VEH_EVENTS])

    df = con.execute(f"""
        SELECT
            character_accountId  AS accountId,
            character_location_x AS x,
            character_location_y AS y
        FROM read_parquet('{fsql}')
        WHERE ({evt_filter})
          AND character_accountId IS NOT NULL
          AND character_location_x IS NOT NULL
    """).fetchdf()

    if df.empty:
        continue

    df['matchId'] = match_id

    # 낙하 지점과 merge
    df = df.merge(
        df_drop[['matchId','accountId','x','y']]
               .rename(columns={'x':'drop_x','y':'drop_y'}),
        on=['matchId','accountId'], how='left'
    )

    df['veh_dist'] = np.sqrt(
        (df['x'] - df['drop_x'])**2 +
        (df['y'] - df['drop_y'])**2
    )

    df_max = df.groupby(['matchId','accountId'])['veh_dist'].max().reset_index()
    df_max.rename(columns={'veh_dist':'max_vehicle_distance'}, inplace=True)
    veh_list.append(df_max)

if veh_list:
    df_veh_max = pd.concat(veh_list, ignore_index=True)
    df_veh_max['max_vehicle_distance'] = df_veh_max['max_vehicle_distance'] / 100  # cm → m
    print(f'차량 이동 피처: {len(df_veh_max):,}명  평균: {df_veh_max["max_vehicle_distance"].mean():.1f}m')
else:
    df_veh_max = pd.DataFrame(columns=['matchId','accountId','max_vehicle_distance'])
    print('차량 이벤트 없음')

차량 이동 계산 중
차량 이벤트명:

                              _T    n
0               LogVehicleDamage  918
1              LogVehicleDestroy    4
2                 LogVehicleRide  509
3  LogItemPickupFromVehicleTrunk   23
4                LogVehicleLeave  508
5       LogItemPutToVehicleTrunk   32

100%|██████████| 3463/3463 [03:24<00:00, 16.93it/s]

차량 이동 피처: 235,542명  평균: 5768.4m

In [8]:
# STEP 6: 플레이어별 피처 집계
print('피처 집계 중')

# rotation_timing_score: 안정 구간 vs 수축 구간 자기장 거리 비율
# 0 = 선점형 (안정 구간에 이미 자기장 안에 있음)
# 1 = 후행형 (수축 구간에 이동)
SHRINK_PHASES = [1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
STABLE_PHASES = [1.0, 2.0, 3.0, 4.0, 5.0]

def calc_rotation_timing(grp):
    pre  = grp[grp['isGame'].isin(STABLE_PHASES)]['dist_to_safe_center'].mean()
    post = grp[grp['isGame'].isin(SHRINK_PHASES)]['dist_to_safe_center'].mean()
    if pd.isna(pre) or pd.isna(post):
        return np.nan
    return pre / (pre + post + 1e-6)


features = []
grouped  = df_pos_full.groupby(['matchId','accountId'])
print(f'총 {grouped.ngroups:,}명 처리 예정')

for (match_id, account_id), grp in tqdm(grouped, total=grouped.ngroups):
    grp = grp.sort_values('elapsedTime')
    safe_r = grp['safe_radius'].replace(0, np.nan)  # 0 으로 나누기 방지

    features.append({
        'matchId':                  match_id,
        'accountId':                account_id,
        'rotation_timing_score':    calc_rotation_timing(grp),
        'vehicle_use_ratio':        grp['isInVehicle'].mean(),
        'bluezone_exposure_ratio':  grp['isInBlueZone'].mean(),
        'safezone_proximity_mean':  grp['dist_to_safe_center'].mean(),
        'safezone_edge_ratio':      (grp['dist_to_safe_center'] / (safe_r + 1e-6)).mean(),
        'altitude_variance':        grp['z'].std(),
        'survival_time':            grp['elapsedTime'].max() - grp['elapsedTime'].min(),
        'total_movement':           np.sqrt(grp['x'].diff()**2 + grp['y'].diff()**2).sum(),
    })

df_features = pd.DataFrame(features)
print(f'피처 테이블: {df_features.shape}')
display(df_features.head(3))

피처 집계 중
총 234,245명 처리 예정

100%|██████████| 234245/234245 [04:12<00:00, 927.91it/s]

피처 테이블: (234245, 10)

,matchId,accountId,rotation_timing_score,vehicle_use_ratio,bluezone_exposure_ratio,safezone_proximity_mean,safezone_edge_ratio,altitude_variance,survival_time,total_movement
0,000c936c-b00b-47f0-9e1b-493d589f99bd,account.0038d4bb0dcc4a05b68d39589da0236e,NaN,0.000000,0.000000,2783.816730,0.004783,125.964431,130.0,12359.044434
1,000c936c-b00b-47f0-9e1b-493d589f99bd,account.0616e81ecec241c2915f1bbc52b6958e,0.566873,0.065359,0.176471,1492.732054,0.007371,16076.135434,1513.0,796011.108843
2,000c936c-b00b-47f0-9e1b-493d589f99bd,account.0901bd6b4a6942d894cddab5aa0907f5,NaN,0.000000,0.000000,2212.186712,0.003801,223.228081,199.0,31892.819979

In [9]:
# STEP 7: 모든 피처 병합
df_all = df_features\
    .merge(
        df_drop[['matchId','accountId','drop_distance_from_path','x','y']]
               .rename(columns={'x':'drop_x','y':'drop_y'}),
        on=['matchId','accountId'], how='left'
    )\
    .merge(
        df_density[['matchId','accountId','early_enemy_density']],
        on=['matchId','accountId'], how='left'
    )\
    .merge(
        df_veh_max,
        on=['matchId','accountId'], how='left'
    )

print(f'통합 피처: {df_all.shape}')
display(df_all.describe())

통합 피처: (234245, 15)

,rotation_timing_score,vehicle_use_ratio,bluezone_exposure_ratio,safezone_proximity_mean,safezone_edge_ratio,altitude_variance,survival_time,total_movement,drop_distance_from_path,drop_x,drop_y,early_enemy_density,max_vehicle_distance
count,191511.000000,234245.000000,234245.000000,234245.000000,234245.000000,233616.000000,234245.000000,2.342450e+05,234221.000000,234229.000000,234229.000000,234225.000000,234229.000000
mean,0.548925,0.137475,0.053981,1480.103032,0.006150,3024.233565,793.010267,3.675563e+05,770.251153,412352.208156,378166.768322,5.081234,5772.040752
std,0.079558,0.143765,0.104631,753.790385,0.317657,4999.533771,492.098358,3.128592e+05,473.431427,157326.443401,137836.564376,6.001977,1686.508207
min,0.064471,0.000000,0.000000,48.405534,0.000083,0.000000,0.000000,0.000000e+00,0.015580,7231.764648,2598.840088,0.000000,224.710265
25%,0.497813,0.000000,0.000000,876.032325,0.003383,352.939962,329.000000,4.940671e+04,366.950968,322427.281250,286482.593750,0.000000,4517.794020
50%,0.544130,0.110092,0.000000,1301.440472,0.004628,1131.103334,818.000000,3.482769e+05,745.191137,412268.000000,349542.406250,4.000000,5679.207116
75%,0.600355,0.236364,0.060606,2009.932331,0.005817,2433.027424,1194.000000,5.956895e+05,1139.362729,546861.375000,474434.812500,8.000000,7009.825276
max,0.973738,1.000000,1.000000,5443.931022,123.962172,73967.948254,1875.000000,2.428406e+06,3721.312540,785295.375000,751826.000000,50.000000,10581.265627

In [10]:
# STEP 8: matches 데이터 조인
# 날짜 필터 적용 (DATE_START ~ DATE_END)
# playerId -> accountId rename 후 조인
print('matches 데이터 로드 중')

mat_files = [
    f for f in sorted(glob.glob(os.path.join(BASE_DIR, 'matches_*.csv')))
    if DATE_START <= os.path.basename(f).replace('.csv','').split('_')[-1] <= DATE_END
]
print(f'matches 파일: {len(mat_files)}개')

df_matches = pd.concat([pd.read_csv(f) for f in mat_files], ignore_index=True)

if 'win_flag' not in df_matches.columns:
    df_matches['win_flag']   = (df_matches['winPlace'] == 1).astype(int)
if 'top3_flag' not in df_matches.columns:
    df_matches['top3_flag'] = (df_matches['winPlace'] <= 10).astype(int)

# playerId -> accountId
df_matches = df_matches.rename(columns={'playerId': 'accountId'})

# 타입 통일
df_all['matchId']       = df_all['matchId'].astype(str)
df_all['accountId']     = df_all['accountId'].astype(str)
df_matches['matchId']   = df_matches['matchId'].astype(str)
df_matches['accountId'] = df_matches['accountId'].astype(str)

df_final = df_all.merge(
    df_matches[['matchId','accountId','kills','damageDealt','winPlace',
                'win_flag','top3_flag','timeSurvived',
                'walkDistance','rideDistance','heals','boosts']],
    on=['matchId','accountId'], how='left'
)

join_rate = df_final['winPlace'].notna().mean()
print(f'최종: {df_final.shape}  조인률: {join_rate:.1%}')

if join_rate < 0.5:
    print('경고: 조인률이 50% 미만입니다. matchId/accountId 형식을 확인하세요.')

display(df_final.head(3))


# ── matches 기반 파생 피처 계산 ──────────────────────────────
# kill_rate     : 분당 킬 수 (timeSurvived 초 단위)
# move_speed    : 이동속도 m/s (walkDistance cm → m 변환)
# heal_boost_use: 분당 힐+부스터 사용 횟수 (생존시간 정규화)
df_final['kill_rate']      = df_final['kills'] / (df_final['timeSurvived'] / 60 + 1e-9)
df_final['move_speed']     = (df_final['walkDistance'] / 100) / (df_final['timeSurvived'] + 1e-9)
df_final['heal_boost_use'] = (
    (df_final['heals'].fillna(0) + df_final['boosts'].fillna(0))
    / (df_final['timeSurvived'] / 60 + 1e-9)
)

print(f'파생 피처 생성 완료:')
print(f'  kill_rate      — 중앙값: {df_final["kill_rate"].median():.4f} (킬/분)')
print(f'  move_speed     — 중앙값: {df_final["move_speed"].median():.4f} (m/s)')
print(f'  heal_boost_use(분당) — 중앙값: {df_final["heal_boost_use"].median():.3f} (회/분)')

matches 데이터 로드 중
matches 파일: 28개
최종: (234245, 25)  조인률: 91.7%

,matchId,accountId,rotation_timing_score,vehicle_use_ratio,bluezone_exposure_ratio,safezone_proximity_mean,safezone_edge_ratio,altitude_variance,survival_time,total_movement,...,kills,damageDealt,winPlace,win_flag,top3_flag,timeSurvived,walkDistance,rideDistance,heals,boosts
0,000c936c-b00b-47f0-9e1b-493d589f99bd,account.0038d4bb0dcc4a05b68d39589da0236e,NaN,0.000000,0.000000,2783.816730,0.004783,125.964431,130.0,12359.044434,...,0.0,0.000,15.0,0.0,0.0,208.0,238.57861,0.0000,0.0,1.0
1,000c936c-b00b-47f0-9e1b-493d589f99bd,account.0616e81ecec241c2915f1bbc52b6958e,0.566873,0.065359,0.176471,1492.732054,0.007371,16076.135434,1513.0,796011.108843,...,3.0,235.884,2.0,0.0,1.0,1610.0,4001.66920,5127.8877,13.0,7.0
2,000c936c-b00b-47f0-9e1b-493d589f99bd,account.0901bd6b4a6942d894cddab5aa0907f5,NaN,0.000000,0.000000,2212.186712,0.003801,223.228081,199.0,31892.819979,...,0.0,0.000,14.0,0.0,0.0,265.0,538.56150,0.0000,0.0,1.0

파생 피처 생성 완료:
  kill_rate      — 중앙값: 0.0000 (킬/분)
  move_speed     — 중앙값: 0.0192 (m/s)
  heal_boost_use(분당) — 중앙값: 0.306 (회/분)

In [11]:
# STEP 9: 저장 및 최종 검증
# ──────────────────────────────────────────────────────────
# [피드백 반영]
# 1. (matchId, accountId) 중복 0 검증
# 2. 기대 row 수 범위 체크 (급증/급감 감지)
# 3. REQUIRED_COLS 스키마 누락 컬럼 즉시 실패
# ──────────────────────────────────────────────────────────

# ── 스키마 검증: config.py의 REQUIRED_COLS 기준 ──
missing_cols = [c for c in REQUIRED_COLS if c not in df_final.columns]
if missing_cols:
    raise RuntimeError(
        f"스키마 불일치 — 누락 컬럼 {len(missing_cols)}개:\n"
        + "\n".join(f"  - {c}" for c in missing_cols)
        + "\n→ 01_data_pipeline 수정 또는 config.py REQUIRED_COLS 갱신 필요"
    )
print(f" 스키마 검증 통과: {len(REQUIRED_COLS)}개 컬럼 모두 존재")

# ── 중복 키 검증 ──
dup = df_final.duplicated(subset=['matchId', 'accountId'])
if dup.any():
    raise RuntimeError(
        f" (matchId, accountId) 중복 {dup.sum()}건 발견\n"
        f"  → drop_duplicates 또는 join 로직 확인 필요"
    )
print(f" 중복 키 검증 통과: (matchId, accountId) 모두 유일")

# ── Row 수 검증 (기대 범위: 매치당 40~64명, 최소 1,000명 이상) ──
n_rows    = len(df_final)
n_matches = df_final['matchId'].nunique()
avg_per_match = n_rows / n_matches if n_matches > 0 else 0

if avg_per_match < 20 or avg_per_match > 70:
    print(f"  경고: 매치당 평균 플레이어 수 {avg_per_match:.1f}명 — 정상 범위(20~70) 벗어남")
    print(f"   join 로직이나 필터 조건 확인 권장")
else:
    print(f" Row 수 검증 통과: {n_rows:,}명 / {n_matches:,}매치 (평균 {avg_per_match:.1f}명/매치)")

# ── 저장 ──
out = TRUTH_TABLES['erangel_features']
df_final.to_parquet(out, index=False)
print(f" 저장 완료: {out}")
print(f" 크기: {df_final.shape[0]:,}행 × {df_final.shape[1]}열")

# ── 결측치 현황 ──
missing = df_final.isnull().mean().sort_values(ascending=False)
missing_df = missing[missing > 0].rename('결측비율').map('{:.1%}'.format).to_frame()
if len(missing_df):
    print('\n결측치 현황:')
    display(missing_df)
else:
    print('\n 결측치 없음')

# ── 핵심 피처 기초 통계 ──
key_features = [
    'drop_distance_from_path', 'early_enemy_density',
    'rotation_timing_score', 'vehicle_use_ratio',
    'bluezone_exposure_ratio', 'safezone_proximity_mean',
    'safezone_edge_ratio', 'altitude_variance',
    'max_vehicle_distance',
]
available = [c for c in key_features if c in df_final.columns]
print('\n핵심 피처 기초 통계:')
display(df_final[available].describe().T)

print('\n→ 02_clustering.ipynb 로')

 스키마 검증 통과: 26개 컬럼 모두 존재
 중복 키 검증 통과: (matchId, accountId) 모두 유일
 Row 수 검증 통과: 234,245명 / 3,463매치 (평균 67.6명/매치)
 저장 완료: C:\배그분석\analysis_output\erangel_features.parquet
 크기: 234,245행 × 28열

결측치 현황:

                          결측비율
rotation_timing_score    18.2%
move_speed                8.3%
kill_rate                 8.3%
boosts                    8.3%
timeSurvived              8.3%
walkDistance              8.3%
rideDistance              8.3%
top3_flag                 8.3%
damageDealt               8.3%
winPlace                  8.3%
win_flag                  8.3%
kills                     8.3%
heal_boost_use            8.3%
heals                     8.3%
altitude_variance         0.3%
drop_distance_from_path   0.0%
early_enemy_density       0.0%
drop_x                    0.0%
drop_y                    0.0%
max_vehicle_distance      0.0%

핵심 피처 기초 통계:

,count,mean,std,min,25%,50%,75%,max
drop_distance_from_path,234221.0,770.251153,473.431427,0.015580,366.950968,745.191137,1139.362729,3721.312540
early_enemy_density,234225.0,5.081234,6.001977,0.000000,0.000000,4.000000,8.000000,50.000000
rotation_timing_score,191511.0,0.548925,0.079558,0.064471,0.497813,0.544130,0.600355,0.973738
vehicle_use_ratio,234245.0,0.137475,0.143765,0.000000,0.000000,0.110092,0.236364,1.000000
bluezone_exposure_ratio,234245.0,0.053981,0.104631,0.000000,0.000000,0.000000,0.060606,1.000000
safezone_proximity_mean,234245.0,1480.103032,753.790385,48.405534,876.032325,1301.440472,2009.932331,5443.931022
safezone_edge_ratio,234245.0,0.006150,0.317657,0.000083,0.003383,0.004628,0.005817,123.962172
altitude_variance,233616.0,3024.233565,4999.533771,0.000000,352.939962,1131.103334,2433.027424,73967.948254
max_vehicle_distance,234229.0,5772.040752,1686.508207,224.710265,4517.794020,5679.207116,7009.825276,10581.265627

→ 02_clustering.ipynb 로